name: лаба 5

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    name: прогнать тесты на Ubuntu и Windows
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]


    steps:
      - name: скачать репозиторий
        uses: actions/checkout@v4

      - name: установить Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.x"
      - name: прогон тестов
        working-directory: geometric_lib
        run: python -m unittest discover -s tests
